name: Unity License Request
on: workflow_dispatch
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.0f1  # set to your Unity version
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-file
          path: Unity_*.alf